# Generated by Django 4.0.5 on 2022-06-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_title', models.CharField(max_length=255, verbose_name='Academic title')),
                ('given_name', models.CharField(max_length=255, verbose_name='Given name')),
                ('family_name', models.CharField(max_length=255, verbose_name='Family name')),
                ('gender', models.CharField(max_length=255, verbose_name='Gender')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('telephone', models.CharField(max_length=255, verbose_name='Telephone')),
                ('academic_status', models.CharField(max_length=255, verbose_name='Academic status')),
                ('country_origin', models.CharField(max_length=255, verbose_name='Country origin')),
                ('current_location', models.CharField(max_length=255, verbose_name='Current location')),
                ('profession', models.CharField(max_length=255, verbose_name='Profession')),
                ('university', models.CharField(max_length=255, verbose_name='University')),
                ('type_participation', models.CharField(max_length=255, verbose_name='Type participation')),
                ('presentation_title', models.CharField(max_length=255, verbose_name='Presentation title')),
                ('abstract', models.TextField(verbose_name='Abstract')),
                ('short_cv', models.TextField(verbose_name='Short CV')),
                ('presentation_upload', models.FileField(upload_to='', verbose_name="Telegram's ID")),
                ('portrait', models.FileField(upload_to='', verbose_name='Portrait')),
            ],
        ),
    ]
